### ISSUE TITLE
老哥，这里面的所有内容你都背下来了吗？

### ISSUE THREAD

**Issue by XingYu9902** [Neyzoter/Anki-Backup#1]
下载看了一下，这内容有点多啊

**Comment by Neyzoter** [comment]
理解+记忆。
卡片里边有一些和我项目相关的知识点，可能会根据简历深入问，比如InfluxDB、MongoDB之类的。如果项目中没有涉及到，可以跳过。
重点可以看卡片内容的Java（如果有时间可以深入看《深入理解Java虚拟机》和《Java并发编程的艺术》，并自行做卡片笔记）、计算机基础（操作系统、计算机网络、计算机组成原理）、MySql、算法题。
